branches:
  - gwl
  - ar6
  # - tread
ar6_variables:
  - prec
  - temp_min
  - temp_max
  - temp_avg
gwls:
  - GWL1.5
  - GWL2.0
  - GWL3.0
  - GWL4.0
ssp_scenarios:
  - historical
  - ssp126
  - ssp245
  - ssp370
  - ssp585
tread_variables:
  - wind_spd
  - sun
  - temp_min
  - temp_max
  - prec
  - rel_humid