branches:
  # - GWL
  # - AR6
  - TREAD

# Slicing date range
start_date: 
end_date: 

# Slicing configuration:
spatial_resolution: "pinpoint"  # "1deg"
temporal_resolution: "daily" # "weekly"
exclude_models:
